spring:
  main:
    banner_mode: off
  application:
    name: app

server:
  port: ${port:8080}
  use-forward-headers: true
  compression:
    enabled: false
    min-response-size: 8192
    mime-types:
      - application/json
  undertow:
    worker-threads: 8

logging:
  level:
    root: INFO
